/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica5_pcd;

import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author usuario
 */
public class Generador extends java.awt.Frame {

    /**
     * Creates new form Generador
     */
    public Generador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Generador Ventana = new Generador();
        CanvasGenerador cv = new CanvasGenerador();
        Tienda TiendaPractica = new Tienda(cv);
        Random aleatorio = new Random();
        int comprador_o_reparacion;

        Ventana.setSize(1280, 768);
        Ventana.add(cv);
        //cv.setVisible(true);
        Ventana.setVisible(true);

        Thread[] hilos = new Thread[10];

        for (int i = 0; i < 10; i++) {
            try {
                comprador_o_reparacion = aleatorio.nextInt(10) + 1;
                if (comprador_o_reparacion <= 5) {//60% reparadores
                    hilos[i] = new Thread(new Reparar(TiendaPractica,cv));
                    
                }
                else{
                    hilos[i] = new Comprar(TiendaPractica,cv);
                }
                
                hilos[i].start();
                Thread.sleep((aleatorio.nextInt(2) + 1) * 1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Generador.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        for (int i = 0; i < 10; i++) {
            try {
                hilos[i].join();
            } catch (InterruptedException ex) {
                Logger.getLogger(Generador.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
